export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 533,
};

export const PROVIDERS = {
  ELEVENLABS: 'elevenlabs',
  OPENAI: 'openai',
  GOOGLE: 'google',
};

export const DEFAULT_USER_QUOTA = {
  FREE_CHARACTERS: 10000,
  PRO_CHARACTERS: 100000,
  ENTERPRISE_CHARACTERS: 1000000,
};

export const AUDIO_FORMATS = {
  MP3: 'mp3',
  WAV: 'wav',
  OGG: 'ogg',
};

export const STORAGE_BUCKET = process.env.SUPABASE_AUDIO_BUCKET || 'tts-audio';
